### ISSUE TITLE
个别字段ios和android 两个平台有差异

### ISSUE THREAD

**Issue by oillamp** [magicismight/react-native-mtj#1]
hi，楼主，非常感谢这个插件，封装了原生的sdk，用起来方便许多

有一个小问题，希望能帮助解决一下，

logSendWifiOnly，enableExceptionLog，enableDebugOn 

这三个字段，

在ios 端，使用整形0和1表示false/true

在android端，使用boolean类型true,false,

能否将这个统一一下，方便js层面的调用，非常感谢

PS: 不懂ios, 只是看了下源码，说的有不对的地方，还请指正出来，谢谢

**Comment by magicismight** [comment]
应该影响不大，rn会自动转换的，在js层调用的时候都是统一用true,false
