### ISSUE TITLE
没有文档吗，这个是怎么用的啊

### ISSUE THREAD

**Issue by tofrookie** [magicismight/react-native-mtj#3]
能告诉我怎么用的吗 谢谢了

**Comment by magicismight** [comment]
这个是个公司内部使用的类库开源出来的，暂时没有时间编写文档
https://github.com/magicismight/react-native-mtj/blob/master/mtj.js
所有可调用的接口可以参考这里暴露出来的方法
原生代码安装请结合百度的文档进行安装

```
import {
    start,
    pageViewChangeWithName
} from 'react-native-mtj';

// 一个简单的页面数据统计
start();
pageViewChangeWithName('页面名称');
```

**Comment by tofrookie** [comment]
undefined is not an object(evaluating Mtj.start)

是不是还要装什么包，引用什么

**Comment by tofrookie** [comment]
配好了。。。但并没有统计出来。。不知道哪里出了问题
你项目下面有一个libs/Baidu_Mtj_xxx.jar，我是用你的还是自己下一个
把你那个删掉

**Comment by tofrookie** [comment]
配好了，并没有效果啊
`import {
    start,
    pageViewChangeWithName
} from 'react-native-mtj';

// 一个简单的页面数据统计
start('我的appkey?');
pageViewChangeWithName('页面名称');`

**Comment by magicismight** [comment]
```
        start(appkey, {
            enableDebugOn: true
        });
```
你把调试模式打开看一下

**Comment by tofrookie** [comment]
哦，打开了，没有报错，看哪里？

**Comment by magicismight** [comment]
看调用 pageViewChangeWithName('页面名称'); 的时候有没有调试信息输出
如果有的话就可以用了，等网站上的数据同步就好了

**Comment by tofrookie** [comment]
并没有什么信息输出啊

**Comment by tofrookie** [comment]
我的MainActivity.java里
```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new RNMtjPackage(this),//这里这么写对吗
      );
    }
```

**Comment by magicismight** [comment]
对的，是这样写的，没什么报错或者提示吗？

**Comment by magicismight** [comment]
ios上面百度统计的提示前缀是 [BaiduMobStat]

**Comment by magicismight** [comment]
下班了，如果还是不行你可以在js里面调一下，看下是那步没进去
还不行我明天再帮你看

**Comment by tofrookie** [comment]
好的，我来调试一下，我先用的是安卓，之后再搞ios

**Comment by tofrookie** [comment]
log显示
 *******onPageStart=主页
 AnalysisPageStart
 遗漏StatService.onPageEnd() || missing StatService.onPageEnd()
 is_first_resume=false

**Comment by chenillwang** [comment]
请问一下，我们这边现在有个开发需求，针对固定操作进行埋点，想问一下，用你这个合适么？
